### ISSUE TITLE
Code improofment

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#107]
(Reffering to the MCDU branch)
I'ld recommend you to do a hide and show all function which you can call and then just hide show the needed lines.
Same for setting colors, arrows and fonts... this will reduce workload and risk of mistakes.

I'ld also create a set of predefined colors...

**Comment by it0uchpods** [comment]
Hi,
Your comment just pushes me further to move WIP work private.

It's an extremely rough version of the MCDU Canvas, and is by no-means final (and I wouldn't allow such code into master). I was too tired to figure out a better way, but wanted to see if my Simple MCDU svg was doable for basic pages. 

I'll be rewriting it in the next few days.

Also, a hindering factor in my original plan, it that I cannot see the state of an object, like getColor().

Also, that is not how canvas works, if I did your suggestion, every time the loop runs (0.05), it would show all, then hide some, causing the hidden ones to flicker.

Kind Regards,
Josh

PS: Again, these things (recommendations) should be in forum -- not here!

**Comment by merspieler** [comment]
Well... i mean just a function call insted of writing 6 times `me["Simple_Ln"].setColor(1,1,1);` to be able to write `me.setAllColor(1,1,1);` and the function does the rest.

... btw i've just tested where you respond faster... here or in the forum :P

**Comment by it0uchpods** [comment]
But I can only use that for that page, each page would need it's own function then -- so whats the point?
Each page, the lines have different colors -- as I said -- I will find a much better way to manage it when I have more time/energy, and since no-one is using it, it wasn't my top priority. Plus, on some pages, the color will be in an if statement to the value of an internal MCDU property (such as the FMGC one on MCDU MENU). I have explored quite a few possibilities, even doing the page switching outside the loop, but they all cause problems.

Well, here sends a mail, which makes my phone buzz, and I'm usually free around this time.

I don't appreciate rude comments like that. Using a rough draft, that wasn't indented to be efficient?

This is my last comment on the matter for now. I assure you a better way will be found.

Kind Regards,
Josh

**Comment by merspieler** [comment]
You can still overwrite the settings of the set all function if needed... but your the dev and it's your decision... I just wanted to give some advice(I've made the same mistake my own...)

And sorry if i sounded rude... that wasn't my intention.

**Comment by it0uchpods** [comment]
`You can still overwrite the settings of the set all function if needed`
I don't exactly know what you mean.

I just had the idea, for example, to send the colors needed, like ["w","w","g"] for white white green, in a top to bottom, then left to right order.... I'll experiment. Same could work with hiding I guess. 

No problem -- and I usually don't mind, except when it's something I've just thrown together in a WIP branch not intended for use.

Kind Regards,
Josh

**Comment by merspieler** [comment]
i mean... 
`
setAll_L_ColorsTo("w"); # sets all colors to white, most used color in this example
me["Simple_L5"].setColor("g"); # sets only the 5th line to green
`
this would do the job of 5 lines by the current structure.
The function would look like that:
`
setAll_L_ColorsTo(color)
{
    # useage of a for loop is possible as well
    me["Simple_L1"].setColor(color);
    me["Simple_L2"].setColor(color);
    me["Simple_L3"].setColor(color);
    me["Simple_L4"].setColor(color);
    me["Simple_L5"].setColor(color);
    me["Simple_L6"].setColor(color);
}
`

Yes... it works for hiding, fonts and size.

the array of colors wasn't my intention but would be a possible and clean option too

**Comment by it0uchpods** [comment]
Could do that too, but very few pages it works like that. (maybe 3 or so)

Kind Regards,
Josh
