### ISSUE TITLE
Bug: AP almost levels out in (OP) DES to reduce speed

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#27]
### Expected Behavior
AP just reduces decent rate

### Current Behavior
AP levels almost out

### Steps to Reproduce
1. Just decent through FL100 with managed speed and observe the speed

### Reference
https://www.youtube.com/watch?v=bjGT9aJU6jo&t=240

**Comment by legoboyvdlp** [comment]
As the speedbrake is extended, this probably could cause the descent?

**Comment by it0uchpods** [comment]
Invalid, because I cannot find the schematics or such of how the OP DES mode exactly works. So, I have guessed based on what I know about it. We know it keeps speed with pitch, this is what mine does. I cannot make the autopilot perform EXACTLY like the real thing without seeing schematics or something of how the real one works. I may in the future try to redo it using rate of accel or decel, which would allow to change how much the speed change is, but right now I am not doing that yet. Not saying its wontfix, but I'm not marking as a bug because it does what I intended it to do.

Bets Regards,
Josh

**Comment by merspieler** [comment]
Well even if speed breaks are used the IDG levels off

**Comment by merspieler** [comment]
So, I have guessed based on what I know about it...
Study level???

**Comment by it0uchpods** [comment]
@merspieler Go find me AP schematics, then I'll program is exactly as Airbus did. Until then, I can only guess. I don't think you actually read my reply.

**Comment by merspieler** [comment]
Another example:
https://www.youtube.com/watch?v=ZNTnwaWa5DU

If I find a better description than in the FCOM I might consider and link it here

**Comment by legoboyvdlp** [comment]
@merspieler 
you don't have a Scribd account, do you?

if so, that will help a lot, there are many, many documents there.

**Comment by merspieler** [comment]
No, i don't... iirc it has blocked tor acces or i disagreed with the TOS or PP

**Comment by pumuckl11** [comment]
@merspielers's finding: I second that - the principle also applies to climb phase. There is no need to aim at the target speed in the shortest time possible by almost leveling out. An approximate solution is to look for the speed-gradient. A change of 10 kts per 10 sec (speed-prediction!) for example could do the trick. What do you think?

**Comment by pumuckl11** [comment]
Got your point. In case I find something useful I'll drop it here.

**Comment by it0uchpods** [comment]
Thanks.

J
