### ISSUE TITLE
Missing distance from ILS

### ISSUE THREAD

**Issue by I-NICO** [it0uchpods/IDG-A32X#76]
Impossible to see distance from ILS station.

### Expected Behavior
With PFD in LS mode the distance displayed at the bottom L corner should be the distance from the currently tuned ILS station.

### Current Behavior
Distance from VOR1 is displayed instead.

### Steps to Reproduce
1 Select LS mode on the PDF
2 Tune LS frequency on the closest ILS station.
3 Tune VOR1 on a random VOR station,
4 The ILS alignment is displayed correctly but at the bottom L corner you can still read the distance from VOR1 instead of the distance from ILS station.

**Comment by Wecsje** [comment]
We are aware of this feature missing, but the aircraft is still in active development. We will probably not fix this issue soon.

Regards,

Charlie (Wecsje)

**Comment by it0uchpods** [comment]
To further expand, this feature will not be added to the current PFD. The Canvas PFD is currently in development, and that is the 4th thing down on my list of things to add. Once the Canvas PFD is ready, it will work.

I'm closing this, because it will be fixed in the Canvas PFD update in some weeks.

Kind Regards,
Josh
