### ISSUE TITLE
Change MCDU text

### ISSUE THREAD

**Issue by merspieler** [it0uchpods/IDG-A32X#77]
This is more a featur request than a bug.

### Expected Behavior
When in the MCDU i perform an action which isn't implemented yet, it sould display `NOT IMPLEMENTED`

### Current Behavior
Now it shows NOT ALLOWED which is confusing cause i don't know if i just entered the wrong things into the scratch pad or the featur isn't implemented.

### Possible Solution
Change the text for not implemented features

### Steps to Reproduce
Just an example, where it happens:
1. MCDU MENU
2. 2nd line key <ACARS
The line should show NOT IMPLEMENTED instead of NOT ALLOWED

**Comment by it0uchpods** [comment]
Hi
I won't implement this because right now, I can check if its on a supported function or not, else show NOT ALLOWED. I'd have to add each and everything which is not supported to it, and then change later. It would take alot of work, and I don't want to duplicate work, sorry. By V1.0, I can add this if there is anything still not implemented.

Kind Regards,
Josh

**Comment by merspieler** [comment]
OK. It was just an idea
